Feature/readme.md
stahljohnmark/whatsfordinner pull request #17
Opened 2022-01-18 05:03 UTC by nmemarcoding

read me is ready with user story acceptance criteria mock up images and live link

2022-01-18 11:48 UTC, stahljohnmark approved these changes
Looks good, I found a few items we should probably update. For example, Whatsfordinner should be separated. The story should be bold for the reason why the site was created. Its kind of like a paper so its probably going to need a couple more updates from everyone before we present. Otherwise LGTM

2022-01-18 14:18 UTC, hjohnsick commented on README.md
> +* SO THAT I can preapr meal and drink with my ingredients
spelling mistake on line 5, should be prepare.  SO THAT I can prepare a meal

2022-01-18 14:20 UTC, hjohnsick commented on README.md
> +* THEN I present with pop up modal for recipe
THEN I am presented with a pop up

2022-01-18 14:21 UTC, hjohnsick commented on README.md
> +* WHEN dbclick on star
WHEN I double click

2022-01-18 14:21 UTC, hjohnsick commented on README.md
> +* THEN remove that food or drink from favarit meal or drink
favorite

2022-01-18 14:21 UTC, hjohnsick commented on README.md
> +* THEN display star for favorit meals and drinks
favorite

2022-01-18 14:22 UTC, hjohnsick commented on README.md
> +* WHEN click on favorit meals or drinks star
WHEN I click on favorite

2022-01-18 14:22 UTC, hjohnsick commented on README.md
> +* THEN display all favorits meals or drink
favorites

2022-01-18 14:24 UTC, hjohnsick requested changes
There should be a section for languages/frameworks that includes JavaScript, JQuery, HTML, CSS, and Bulma

2022-01-19 00:36 UTC, stahljohnmark approved these changes
As discussed we should adjust the narrative other than that. LGTM

2022-01-19 01:43 UTC, hjohnsick approved these changes

2022-01-19 01:43 UTC, merged